version: '3.8'
services:
  chroma-db:
    image: chromadb/chroma:latest
    container_name: chroma-db
    volumes:
      - chroma_data:/chroma/.chroma/index
      - ./data/documents:/app/data/documents:rw
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1" ]
      interval: 5s
      timeout: 3s
      retries: 24
volumes:
  chroma_data:
